pipeline {
    agent any

    environment {
        BACKEND_IMAGE = 'backend:test'
        FRONTEND_IMAGE = 'frontend:test'
        DOCKER_HUB_CREDENTIALS = 'adinathDockerHub' 
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Cloning repository...'
                git branch: 'main', url: 'https://github.com/AdyaPatil/Patient-Appointment.git'
            }
        }

        stage('Build Backend Image') {
            steps {
                script {
                    echo 'Building backend Docker image...'
                    sh 'docker build -t $BACKEND_IMAGE -f Dockerfile --target backend .'
                }
            }
        }

        stage('Build Frontend Image') {
            steps {
                script {
                    echo 'Building frontend Docker image...'
                    sh 'docker build -t $FRONTEND_IMAGE -f Dockerfile --target frontend .'
                }
            }
        }

        stage('Push Docker Images') {
            steps {
                script {
                    echo 'Pushing Docker images to Docker Hub...'
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CREDENTIALS) {
                        sh "docker push $BACKEND_IMAGE"
                        sh "docker push $FRONTEND_IMAGE"
                    }
                }
            }
        }

        stage('Deploy Backend') {
            steps {
                echo 'Deploying backend...'
                sh 'docker run -d --name backend -p 8000:8000 -e SQLALCHEMY_DATABASE_URL=mysql+pymysql://user:password@db:3306/database_name $BACKEND_IMAGE'
            }
        }

        stage('Deploy Frontend') {
            steps {
                echo 'Deploying frontend...'
                sh 'docker run -d --name frontend -p 80:80 $FRONTEND_IMAGE'
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
