# Use the official MySQL image from the Docker Hub
FROM mysql:5.7

# Set environment variables for MySQL root password and database name
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=patient_appointment

# Expose port 3306 for MySQL
EXPOSE 3306

# The default command will start MySQL server
CMD ["mysqld"]

